{
  imports = [
    ./blink.nix
    ./conform.nix
    ./dap.nix
    ./gitsigns.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./mini.nix
    ./nvim-autopairs.nix
    ./oil.nix
    ./telescope.nix
    ./treesitter.nix
    ./venv-selector.nix
    ./which-key.nix
  ];
}
